version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldbco
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: '$MYSQLDB_DATABASE'
      MYSQL_USER: 'aziz'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_HOST: '%'
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image:  azizoss/spring-app-twin:second
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&enabledTLSProtocols=TLSv1.2",
        "spring.datasource.username" : "aziz",
        "spring.datasource.password" : "1234",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    #volumes:
     # - type: bind
      #  source: /root/.m2
      #  target: ${PWD}/.m2
    #volumes:
      #- .m2:/root/.m2
    stdin_open: true
    tty: true
    user: root

volumes:
  db:
